# This file configures the generation of static documentation by MkDocs
# based on Markdown source files in the 'docs' directory of the OTP repo.
# This static documentation is built and served by Readthedocs
# at opentripplanner.readthedocs.org

site_name: OpenTripPlanner 2
site_url: https://docs.opentripplanner.org
repo_url: https://github.com/opentripplanner/OpenTripPlanner
docs_dir: docs
site_dir: target/mkdocs
strict: true

plugins:
    - "no-sitemap"
    - search

theme:
    name: material
    features:
        - toc.integrate
        - content.code.copy
        - search.suggest
        - search.highlight
    palette:
        primary: blue
        accent: blue
        scheme: default


extra:
    version:
        provider: mike

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

# MkDocs will automatically discover pages if you don't list them here.
# In that case subdirectories can be used to organize pages.
# The list below organizes them into categories and controls the order.

nav:
- Home: 'index.md'
- About:
    - Product Overview: 'Product-Overview.md'
    - Governance: 'Governance.md'
    - History: 'History.md'
    - Presentations: 'Presentations.md'
    - Deployments: 'Deployments.md'
    - Changelog: 'Changelog.md'
    - Visual Identity: 'Visual-Identity.md'
- 'Usage':
    - Basic Tutorial: 'Basic-Tutorial.md'
    - Getting OTP: 'Getting-OTP.md'
    - Container Image: 'Container-Image.md'
    - System Requirements and Suggestions: 'System-Requirements.md'
    - Configuration:
        - Introduction: 'Configuration.md'
        - Build: 'BuildConfiguration.md'
        - "Boarding Locations": 'BoardingLocations.md'
        - "Street Graph Pruning": 'IslandPruning.md'
        - Router: 'RouterConfiguration.md'
        - Accessibility: 'Accessibility.md'
        - "Route Request": 'RouteRequest.md'
        - "Realtime Updaters" : 'UpdaterConfig.md'
        - "Routing Modes" : "RoutingModes.md"
        - "Logging" : "Logging.md"
    - Preparing OSM Data: 'Preparing-OSM.md'
    - Netex and SIRI: 'Netex-Norway.md'
    - Security: 'Security.md'
    - Troubleshooting: 'Troubleshooting-Routing.md'
    - Comparing OTP2 to OTP1: 'Version-Comparison.md'
    - OTP2 Migration Guide: 'OTP2-MigrationGuide.md'  
- Development:
    - "Developers' Guide": 'Developers-Guide.md'
    - Interfaces and Data Sources: 'Interfaces-Data-Sources.md'
    - Localization: 'Localization.md'
    - Bibliography: 'Bibliography.md'
    - Codestyle: 'Codestyle.md'
    - Sandbox Development: 'SandboxExtension.md'
    - Release Checklist: 'ReleaseChecklist.md'
- Sandbox:
    - About: 'SandboxExtension.md'
    - Actuator API: 'sandbox/ActuatorAPI.md'
    - Direct Transfer Analyzer: 'sandbox/transferanalyzer.md'
    - Google Cloud Storage: 'sandbox/GoogleCloudStorage.md'
    - HSL Legacy GraphQL API: 'sandbox/LegacyGraphQLApi.md'
    - Transmodel(NeTEx) GraphQL API: 'sandbox/TransmodelApi.md'
    - SIRI Updaters: 'sandbox/SiriUpdater.md'
    - SIRI Updater (Azure): 'sandbox/SiriAzureUpdater.md'
    - Vehicle Rental Service Directory API support: 'sandbox/VehicleRentalServiceDirectory.md'
    - Smoove Bike Rental Updator Support: 'sandbox/SmooveBikeRental.md'
    - Mapbox Vector Tiles API: 'sandbox/MapboxVectorTilesApi.md'
    - Flex Routing: 'sandbox/Flex.md'
    - Report API: 'sandbox/ReportApi.md'
    - Interactive OTP Launcher: 'sandbox/InteractiveOtpMain.md'
    - Park and Ride API: 'sandbox/ParkAndRideApi.md'
    - Data Overlay: 'sandbox/DataOverlay.md'
    - Vehicle Parking Updaters: 'sandbox/VehicleParking.md'
    - Vehicle-to-stop Heuristics: 'sandbox/VehicleToStopHeuristics.md'
    - Geocoder API: 'sandbox/GeocoderAPI.md'
    - Travel Time Isochrones: 'sandbox/TravelTime.md'
    - IBI Accessibility Score: 'sandbox/IBIAccessibilityScore.md'
    - Fares: 'sandbox/Fares.md'
    - Ride Hailing: 'sandbox/RideHailing.md'
