name: OTP CI Build

on:
  push:
  pull_request:
    branches:
      - ibi-dev
      - ibi-dev-2.x
jobs:
  build:
    env:
      MAVEN_OPTS: -Xmx2g
    runs-on: ubuntu-latest
    steps:
      # Starting in v2.2 checkout action fetches all tags when fetch-depth=0, for auto-versioning.
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      # Java setup step completes very fast, no need to run in a preconfigured docker container.
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # on windows there are frequent failures caused by page files being too small
      # https://github.com/actions/virtual-environments/issues/785
      - name: Configure Windows Pagefile
        if: matrix.os == 'windows-latest'
        uses: al-cheb/configure-pagefile-action@v1.2


      - name: Prepare coverage agent, build and test
        run: mvn --batch-mode --update-snapshots jacoco:prepare-agent verify jacoco:report -P prettierCheck,unit-tests

      - name: Send coverage data to codecov.io
        if: github.repository_owner == 'opentripplanner' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          files: target/site/jacoco/jacoco.xml

      - name: Deploy to Github Package Registry
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev-1.x' || github.ref == 'refs/heads/dev-2.x') && matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode deploy --settings maven-settings.xml -DskipTests -DGITHUB_REPOSITORY=$GITHUB_REPOSITORY -P prettierCheck

      ## IBI start
      # So that the branch name can be reference via $GITHUB_REF_SLUG.
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      # Define AWS profile credentials for use by subsequent steps.
      - name: Add profile credentials to ~/.aws/credentials
        if: github.event_name == 'push'
        run: ./scripts/add-aws-credentials.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      # Build and test deployment.
      - name: Build and Test
        run: mvn clean verify --batch-mode --show-version --update-snapshots -Dgpg.skip
      # Only prepare deploy files on push events to avoid duplicate pushes to s3 when a commit is
      # pushed to a branch with an open pull request.
      - name: Prepare build files for deployment to s3
        if: github.event_name == 'push'
        run: ./scripts/prep-build-for-deploy-from-github-actions.sh
      # Copy build files to AWS.
      - name: Copy build files to the otp-repo bucket
        if: github.event_name == 'push'
        run: |
          aws s3 cp ./deploy s3://otp-repo --recursive --acl public-read
      # Install mkdocs using pip for use by subsequent steps.
      - name: Install mkdocs
        if: github.event_name == 'push' && env.GITHUB_REF_SLUG == 'ibi-dev-2.x'
        run: |
          pip install mkdocs
      # Using mkdocs produce docs for deployment.
# FIXME: there is an error while trying to run enunciate to generate the docs
#      - name: Prepare doc files for deployment to s3
#        if: github.event_name == 'push' && env.GITHUB_REF_SLUG == 'ibi-dev-2.x'
#        run: ./scripts/prep-docs-for-deploy-from-github-actions.sh
#      # If on ibi-dev branch, then upload docs to IBI s3 buckets & cloudfront.
# FIXME: figure out whether the same bucket should be used, or a different one should be used for 2.x docs
#      - name: Upload docs to IBI s3 buckets & cloudfront
#        if: github.event_name == 'push' && env.GITHUB_REF_SLUG == 'ibi-dev-2.x'
#        run: |
#          aws s3 cp ./target/mkdocs s3://otp-docs.ibi-transit.com --recursive --acl public-read
      # Push notification to Teams.
      - name: Notify us of the build status on MS Teams
        # Release https://github.com/toko-bifrost/ms-teams-deploy-card/releases/tag/3.1.2 this matches
        # the full length commit SHA below. This must not be changed without first reviewing the code of the newer
        # version for potential security risks.
        uses: toko-bifrost/ms-teams-deploy-card@dcc94e4ce4088b1e6b6de5c9a3cda4ddcbe97d2e
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MSTEAMS_WEBHOOK }}

  container-image:
    if: github.repository_owner == 'opentripplanner' && github.event_name == 'push' && github.ref == 'refs/heads/dev-2.x'
    runs-on: ubuntu-latest
    needs: build
    env:
      CONTAINER_REPO: docker.io/opentripplanner/opentripplanner
      CONTAINER_REGISTRY_USER: otpbot
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build container image with Jib, push to Dockerhub
        run: mvn --batch-mode compile com.google.cloud.tools:jib-maven-plugin:build -Djib.to.tags=latest,${{ github.sha }}
