name: OTP CI Build
# On [push, pull_request] causes double-builds when creating PRs.
# But triggering on push only will miss pull requests from outside authors.
# The push event's ref is the name of the pushed branch;
# The pull_request event's branch name is the merge target branch.
on:
  push:
    branches:
      - master
      - dev-1.x
      - dev-2.x
      - graphq-docs
  pull_request:
    branches:
      - master
      - dev-1.x
      - dev-2.x
jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # Starting in v2.2 checkout action fetches all tags when fetch-depth=0, for auto-versioning.
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      # nodejs is needed because the dynamic download of it via the prettier maven plugin often
      # times out
      # Example: https://github.com/opentripplanner/OpenTripPlanner/actions/runs/4490450225/jobs/7897533439
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Java setup step completes very fast, no need to run in a preconfigured docker container
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Prepare coverage agent, build and test
        # these are split into two steps because otherwise maven keeps long-running HTTP connections
        # to Maven Central open which then hang during the package phase because the Azure (Github Actions)
        # NAT drops them
        # https://github.com/actions/runner-images/issues/1499
        run: |
          mvn --batch-mode jacoco:prepare-agent test jacoco:report -P prettierCheck -Dprettier.nodePath=node
          mvn --batch-mode package -Dmaven.test.skip -P prettierSkip

      - name: Send coverage data to codecov.io
        if: github.repository_owner == 'opentripplanner'
        uses: codecov/codecov-action@v3.1.1
        with:
          files: target/site/jacoco/jacoco.xml

      - name: Deploy to Github Package Registry
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev-1.x' || github.ref == 'refs/heads/dev-2.x')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode deploy --settings maven-settings.xml -DskipTests -DGITHUB_REPOSITORY=$GITHUB_REPOSITORY -P prettierSkip -P deployGitHub

  build-windows:
    timeout-minutes: 20
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      # on windows there are frequent failures caused by page files being too small
      # https://github.com/actions/virtual-environments/issues/785
      - name: Configure Windows Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
      - name: Run tests
        run: mvn --batch-mode test -P prettierSkip

  docs:
    if: github.repository_owner == 'opentripplanner'
    runs-on: ubuntu-latest
    env:
      REMOTE: docs
      LOCAL_BRANCH: local-pages
      REMOTE_BRANCH: main
      TOKEN: ${{ secrets.CHANGELOG_TOKEN }}
      MASTER_BRANCH_VERSION: 2.3.0

    steps:

      - uses: actions/checkout@v3.3.0
        # this is necessary so that the correct credentials are put into the git configuration
        # when we push to dev-2.x and push the HTML to the git repo
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev-2.x' || github.ref == 'refs/heads/master')
        with:
          token: ${{ secrets.CHANGELOG_TOKEN }}

      - uses: actions/checkout@v3.3.0
        # for a simple PR where we don't push, we don't need any credentials
        if: github.event_name == 'pull_request'

      - name: Install Python dependencies
        run: pip install -r docs/requirements.txt
        
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build main documentation
        if: github.event_name == 'pull_request'
        run: mkdocs build

      - name: Build GTFS GraphQL documentation
        run: |
          npm install -g @magidoc/cli
          magidoc generate

      - name: Deploy docs to Github pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev-2.x' || github.ref == 'refs/heads/master')
        run: |
          git config --global user.name 'OTP Bot'
          git config --global user.email 'bot@opentripplanner.org'
          
          # mkdocs/mike generates a new sitemap.xml.gz for every commit even if the docs have not changed
          # this configures the date of the change to be the date when the docs haven been changed last
          # https://github.com/jimporter/mike/issues/103#issuecomment-1453878471
          export SOURCE_DATE_EPOCH=`git log -1 --format=%ct docs`

          # mike, the versioning plugin for mkdocs, expects there to be a local branch to push to so
          # we are cloning one here and commit to it
          # mike has support for specifing the origin but then it tries to rebase the _local_ gh-pages
          # branch onto the remote which fails. that's the reason for this git hackery.
          
          git remote add $REMOTE https://$TOKEN@github.com/opentripplanner/docs.git 
          git fetch $REMOTE $REMOTE_BRANCH:$LOCAL_BRANCH

          # prefix is the root folder where to deploy the HTML, we use 'en' to emulate the URL
          # structure of readthedocs
          
          if [ ${{ github.ref }} = 'refs/heads/master' ]; 
          then
            mike deploy --branch $LOCAL_BRANCH --prefix en --title=$MASTER_BRANCH_VERSION --update-aliases v$MASTER_BRANCH_VERSION latest
          else
            mike deploy --branch $LOCAL_BRANCH --prefix en dev-2.x
          fi
          git push $REMOTE $LOCAL_BRANCH:$REMOTE_BRANCH

  graphql-code-generation:
    if: github.repository_owner == 'opentripplanner'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run code generator
        working-directory: src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated
        run: |
          yarn install
          yarn generate
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Compile Java code
        run: mvn --batch-mode compile -DskipTests -P prettierSkip

  container-image:
    if: github.repository_owner == 'opentripplanner' && github.event_name == 'push' && github.ref == 'refs/heads/dev-2.x'
    runs-on: ubuntu-latest
    needs:
      - build-windows
      - build-linux
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build container image with Jib, push to Dockerhub
        env:
          CONTAINER_REPO: docker.io/opentripplanner/opentripplanner
          CONTAINER_REGISTRY_USER: otpbot
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          # we give the container two tags
          #   - "latest"
          #   - a string like "2.3_2022-12-12T21-38"
          
          version_with_snapshot=`mvn -q help:evaluate -Dexpression=project.version -q -DforceStdout`
          version=${version_with_snapshot/-SNAPSHOT/}
          image_date=`date +%Y-%m-%dT%H-%M`
          image_version="${version}_${image_date}"
          
          mvn --batch-mode -P prettierSkip compile com.google.cloud.tools:jib-maven-plugin:build -Djib.to.tags=latest,$image_version
