name: Smoke Tests

on:
  push:
    branches:
      - ibi-dev-2.x
  pull_request:
    branches:
      - ibi-dev
      - ibi-dev-2.x
jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: -Xmx2g
    steps:

      - uses: actions/checkout@v2.3.2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Cache OSM files
        uses: actions/cache@v2
        with:
          path: smoke-tests/**/*.pbf
          key: osm

      - name: Build jar file
        run: "mvn --batch-mode clean package test-compile -Dmaven.test.skip -P prettierSkip"

      - name: atlanta - Build graph, run OTP, run smoke tests
        run: "scripts/smoke-tests.sh"

