name: Smoke Tests

on:
  push:
    branches:
      - ibi-dev-2.x
  pull_request:
    branches:
      - ibi-dev
      - ibi-dev-2.x
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx3g

    strategy:
      matrix:
        locations:
          - name: seattle
            sleep: 15
          - name: atlanta
            sleep: 15
          - name: houston
            sleep: 15
          - name: denver
            sleep: 15
          - name: septa
            sleep: 15
          - name: portland
            # have to sleep longer since computing geofencing zones takes a while
            sleep: 70

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build jar file, compile tests
        run: |
          mvn --batch-mode clean package -Dmaven.test.skip -P prettierSkip
          mvn org.apache.maven.plugins:maven-compiler-plugin:testCompile

      - name: Cache OSM files
        uses: actions/cache@v3
        with:
          path: smoke-tests/**/*.pbf
          key: osm-${{ matrix.locations.name }}-2023-02-22
          restore-keys: |
            osm-${{ matrix.locations.name }}

      - name: Run smoke tests
        run: |
          cd smoke-tests
          make build-${{ matrix.locations.name }}

          make run-${{ matrix.locations.name }} &

          # OTP needs a little while to start up so we sleep
          sleep ${{ matrix.locations.sleep }}

          cd ..

          # run the actual smoke tests
          # we run surefire:test in order to not recompile the tests for each city
          mvn surefire:test -Djunit.tags.included="${{ matrix.locations.name }}" -Djunit.tags.excluded="" -P prettierSkip

          # shutting down the OTP instance running in the background (via make)
          killall make

          scripts/smoke-tests.sh ${{ matrix.locations.name }} 15
