name: Smoke Tests

on:
  push:
    branches:
      - ibi-dev-2.x
  pull_request:
    branches:
      - ibi-dev
      - ibi-dev-2.x
jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: -Xmx2g
    steps:

      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache OSM files
        uses: actions/cache@v3
        with:
          path: smoke-tests/**/*.pbf
          key: osm-2022-10-04
          restore-keys: |
            osm-

      - name: Build jar file, compile tests
        run: |
          mvn --batch-mode clean package -Dmaven.test.skip -P prettierSkip
          mvn org.apache.maven.plugins:maven-compiler-plugin:testCompile
        
      - name: "[Atlanta] Build graph, run OTP, run smoke tests"
        run: scripts/smoke-tests.sh atlanta 15

      - name: "[Houston] Build graph, run OTP, run smoke tests"
        run: scripts/smoke-tests.sh houston 15

      - name: "[Denver] Build graph, run OTP, run smoke tests"
        run: scripts/smoke-tests.sh denver 15

      - name: "[SEPTA] Build graph, run OTP, run smoke tests"
        run: scripts/smoke-tests.sh septa 15

      - name: "[Portland] Build graph, run OTP, run smoke tests"
        # have to sleep longer since computing geofencing zones takes a while
        run: scripts/smoke-tests.sh portland 60
